[2023-06-22T13:46:45.554698+00:00 INFO] [plan:243] ################################################################################
[2023-06-22T13:46:45.554993+00:00 INFO] [plan:244] Starting Reliably experiment: https://app.reliably.com/api/v1/organization/423320d0-f114-44d8-ba48-788577b2c4ac/experiments/1f9ee18a-9b03-4e44-b197-def008ec914e/raw
[2023-06-22T13:46:45.987228+00:00 DEBUG] [caching:24] Building activity cache...
[2023-06-22T13:46:45.987431+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-06-22T13:46:45.987998+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-06-22T13:46:45.988108+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-06-22T13:46:45.988682+00:00 DEBUG] [secret:78] Loading secrets...
[2023-06-22T13:46:45.988995+00:00 DEBUG] [secret:103] Done loading secrets
[2023-06-22T13:46:46.170203+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-06-22T13:46:46.170370+00:00 INFO] [experiment:109] Experiment looks valid
[2023-06-22T13:46:46.170434+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-06-22T13:46:46.171208+00:00 DEBUG] [caching:24] Building activity cache...
[2023-06-22T13:46:46.171307+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-06-22T13:46:46.171906+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-06-22T13:46:46.172257+00:00 DEBUG] [secret:78] Loading secrets...
[2023-06-22T13:46:46.172569+00:00 DEBUG] [secret:103] Done loading secrets
[2023-06-22T13:46:46.172860+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-06-22T13:46:46.173346+00:00 INFO] [run:369] Running experiment: Certificate is always valid and has not expired
[2023-06-22T13:46:46.176244+00:00 DEBUG] [__init__:64] Initializing controls
[2023-06-22T13:46:46.176343+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-06-22T13:46:46.176723+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-06-22T13:46:46.177186+00:00 DEBUG] [experiment:423] Configure Reliably's experiment control
[2023-06-22T13:46:46.177889+00:00 DEBUG] [experiment:587] Sending plan '77592d12-7781-4987-a8ef-50abc8ce2d94' status: running
[2023-06-22T13:46:47.056767+00:00 INFO] [experiment:202] Reliably execution: 84953a9b-d5a8-4352-9f15-a66cbe81676d
[2023-06-22T13:46:47.436160+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'running', 'started_on': '2023-06-22T13:46:46.177586+00:00', 'plan_id': '77592d12-7781-4987-a8ef-50abc8ce2d94'}
[2023-06-22T13:46:47.797722+00:00 DEBUG] [experiment:81] Starting Reliably state checker now
[2023-06-22T13:46:47.797895+00:00 INFO] [run:396] Steady-state strategy: default
[2023-06-22T13:46:47.799222+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-06-22T13:46:47.799579+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'experiment'
[2023-06-22T13:46:47.799958+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-06-22T13:46:47.800502+00:00 DEBUG] [run:558] Running steady-state hypothesis before the method
[2023-06-22T13:46:47.801048+00:00 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-06-22T13:46:47.801610+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'hypothesis'
[2023-06-22T13:46:47.802150+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-06-22T13:46:47.802862+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'activity'
[2023-06-22T13:46:47.803424+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-06-22T13:46:47.804010+00:00 INFO] [activity:215] Probe: capture-certificate
[2023-06-22T13:46:48.429891+00:00 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-06-22T13:46:48.676565+00:00 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}'
[2023-06-22T13:46:49.155180+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'activity'
[2023-06-22T13:46:49.155420+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-06-22T13:46:49.155540+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}'}}}
[2023-06-22T13:46:49.155665+00:00 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-06-22T13:46:49.156034+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-06-22T13:46:49.156353+00:00 DEBUG] [tolerances:53] Alt names: {'reliably.com', 'www.reliably.com'} / Expected alt names: ['reliably.com', 'www.reliably.com']
[2023-06-22T13:46:49.156458+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-06-22T13:46:49.156574+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'hypothesis'
[2023-06-22T13:46:49.156758+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-06-22T13:46:49.156864+00:00 INFO] [run:679] Playing your experiment's method now...
[2023-06-22T13:46:49.156995+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'method'
[2023-06-22T13:46:49.157085+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-06-22T13:46:49.157161+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-06-22T13:46:49.157249+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'method'
[2023-06-22T13:46:49.157328+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-06-22T13:46:49.157430+00:00 DEBUG] [run:598] Running steady-state hypothesis after the method
[2023-06-22T13:46:49.157506+00:00 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-06-22T13:46:49.157639+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'hypothesis'
[2023-06-22T13:46:49.157744+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-06-22T13:46:49.157890+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'activity'
[2023-06-22T13:46:49.157973+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-06-22T13:46:49.158072+00:00 INFO] [activity:215] Probe: capture-certificate
[2023-06-22T13:46:49.644955+00:00 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-06-22T13:46:49.799001+00:00 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}'
[2023-06-22T13:46:50.132798+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'activity'
[2023-06-22T13:46:50.133167+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-06-22T13:46:50.133293+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}', 'value': {'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}}}}
[2023-06-22T13:46:50.133414+00:00 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-06-22T13:46:50.133669+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-06-22T13:46:50.133826+00:00 DEBUG] [tolerances:53] Alt names: {'reliably.com', 'www.reliably.com'} / Expected alt names: ['reliably.com', 'www.reliably.com']
[2023-06-22T13:46:50.133948+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-06-22T13:46:50.134042+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'hypothesis'
[2023-06-22T13:46:50.134121+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-06-22T13:46:50.134223+00:00 WARNING] [run:722] Rollbacks were explicitly requested to be played
[2023-06-22T13:46:50.134297+00:00 INFO] [run:959] Let's rollback...
[2023-06-22T13:46:50.134404+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'rollback'
[2023-06-22T13:46:50.134502+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-06-22T13:46:50.134596+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-06-22T13:46:50.134699+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'rollback'
[2023-06-22T13:46:50.134792+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-06-22T13:46:50.134904+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-06-22T13:46:50.135012+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'experiment'
[2023-06-22T13:46:50.135089+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-06-22T13:46:50.135154+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-06-22T13:46:50.135223+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-06-22T13:46:50.135293+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-06-22T13:46:50.135362+00:00 INFO] [experiment:248] Finishing Reliably execution...
[2023-06-22T13:46:50.488253+00:00 DEBUG] [experiment:163] Stopping Reliably state checker now
[2023-06-22T13:46:50.488765+00:00 DEBUG] [experiment:494] Completing execution '84953a9b-d5a8-4352-9f15-a66cbe81676d' status: completed
[2023-06-22T13:46:51.040274+00:00 DEBUG] [experiment:587] Sending plan '77592d12-7781-4987-a8ef-50abc8ce2d94' status: completed
[2023-06-22T13:46:51.362127+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'finished', 'status': 'completed', 'deviated': False, 'plan_id': '77592d12-7781-4987-a8ef-50abc8ce2d94'}
[2023-06-22T13:46:51.929514+00:00 INFO] [experiment:311] Finished Reliably execution. Bye!
[2023-06-22T13:46:51.929829+00:00 DEBUG] [caching:42] Clearing activities cache
