[2023-06-14T12:50:32.879683+00:00 INFO] [plan:243] ################################################################################
[2023-06-14T12:50:32.881224+00:00 INFO] [plan:244] Starting Reliably experiment: https://app.reliably.com/api/v1/organization/423320d0-f114-44d8-ba48-788577b2c4ac/experiments/1f9ee18a-9b03-4e44-b197-def008ec914e/raw
[2023-06-14T12:50:33.354816+00:00 DEBUG] [caching:24] Building activity cache...
[2023-06-14T12:50:33.355011+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-06-14T12:50:33.355160+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-06-14T12:50:33.355243+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-06-14T12:50:33.355349+00:00 DEBUG] [secret:78] Loading secrets...
[2023-06-14T12:50:33.355419+00:00 DEBUG] [secret:103] Done loading secrets
[2023-06-14T12:50:33.461450+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-06-14T12:50:33.461620+00:00 INFO] [experiment:109] Experiment looks valid
[2023-06-14T12:50:33.461689+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-06-14T12:50:33.461760+00:00 DEBUG] [caching:24] Building activity cache...
[2023-06-14T12:50:33.461819+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-06-14T12:50:33.461955+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-06-14T12:50:33.462097+00:00 DEBUG] [secret:78] Loading secrets...
[2023-06-14T12:50:33.462157+00:00 DEBUG] [secret:103] Done loading secrets
[2023-06-14T12:50:33.462213+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-06-14T12:50:33.462335+00:00 INFO] [run:369] Running experiment: Certificate is always valid and has not expired
[2023-06-14T12:50:33.464731+00:00 DEBUG] [__init__:64] Initializing controls
[2023-06-14T12:50:33.464832+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-06-14T12:50:33.464911+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-06-14T12:50:33.465041+00:00 DEBUG] [experiment:423] Configure Reliably's experiment control
[2023-06-14T12:50:33.465297+00:00 DEBUG] [experiment:587] Sending plan '6de80c44-9b7c-4de5-8ff0-7a41f44e8f7b' status: running
[2023-06-14T12:50:34.474203+00:00 INFO] [experiment:202] Reliably execution: 91622163-dbe5-480a-96c4-de18cc5374ca
[2023-06-14T12:50:34.856966+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'running', 'started_on': '2023-06-14T12:50:33.465101+00:00', 'plan_id': '6de80c44-9b7c-4de5-8ff0-7a41f44e8f7b'}
[2023-06-14T12:50:35.352435+00:00 DEBUG] [experiment:81] Starting Reliably state checker now
[2023-06-14T12:50:35.352586+00:00 INFO] [run:396] Steady-state strategy: default
[2023-06-14T12:50:35.353893+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-06-14T12:50:35.354017+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'experiment'
[2023-06-14T12:50:35.354126+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-06-14T12:50:35.354608+00:00 DEBUG] [run:558] Running steady-state hypothesis before the method
[2023-06-14T12:50:35.354834+00:00 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-06-14T12:50:35.355054+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'hypothesis'
[2023-06-14T12:50:35.355232+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-06-14T12:50:35.355451+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'activity'
[2023-06-14T12:50:35.355543+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-06-14T12:50:35.355732+00:00 INFO] [activity:215] Probe: capture-certificate
[2023-06-14T12:50:36.000600+00:00 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-06-14T12:50:36.143883+00:00 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}'
[2023-06-14T12:50:36.667418+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'activity'
[2023-06-14T12:50:36.667653+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-06-14T12:50:36.667768+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}'}}}
[2023-06-14T12:50:36.667893+00:00 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-06-14T12:50:36.668128+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-06-14T12:50:36.668236+00:00 DEBUG] [tolerances:53] Alt names: {'reliably.com', 'www.reliably.com'} / Expected alt names: ['reliably.com', 'www.reliably.com']
[2023-06-14T12:50:36.668316+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-06-14T12:50:36.668410+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'hypothesis'
[2023-06-14T12:50:36.668494+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-06-14T12:50:36.668577+00:00 INFO] [run:679] Playing your experiment's method now...
[2023-06-14T12:50:36.668684+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'method'
[2023-06-14T12:50:36.668769+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-06-14T12:50:36.668849+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-06-14T12:50:36.668937+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'method'
[2023-06-14T12:50:36.669013+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-06-14T12:50:36.669095+00:00 DEBUG] [run:598] Running steady-state hypothesis after the method
[2023-06-14T12:50:36.669173+00:00 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-06-14T12:50:36.669267+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'hypothesis'
[2023-06-14T12:50:36.669380+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-06-14T12:50:36.669488+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'activity'
[2023-06-14T12:50:36.669623+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-06-14T12:50:36.669719+00:00 INFO] [activity:215] Probe: capture-certificate
[2023-06-14T12:50:37.054255+00:00 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-06-14T12:50:37.144218+00:00 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}'
[2023-06-14T12:50:37.521996+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'activity'
[2023-06-14T12:50:37.522390+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-06-14T12:50:37.522620+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}', 'value': {'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}}}}
[2023-06-14T12:50:37.522758+00:00 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-06-14T12:50:37.523145+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-06-14T12:50:37.523270+00:00 DEBUG] [tolerances:53] Alt names: {'reliably.com', 'www.reliably.com'} / Expected alt names: ['reliably.com', 'www.reliably.com']
[2023-06-14T12:50:37.523355+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-06-14T12:50:37.523452+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'hypothesis'
[2023-06-14T12:50:37.523535+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-06-14T12:50:37.523641+00:00 WARNING] [run:722] Rollbacks were explicitly requested to be played
[2023-06-14T12:50:37.523834+00:00 INFO] [run:959] Let's rollback...
[2023-06-14T12:50:37.524442+00:00 DEBUG] [__init__:460] Applying before-control 'reliably' on 'rollback'
[2023-06-14T12:50:37.524572+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-06-14T12:50:37.524659+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-06-14T12:50:37.524817+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'rollback'
[2023-06-14T12:50:37.524943+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-06-14T12:50:37.525097+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-06-14T12:50:37.525311+00:00 DEBUG] [__init__:460] Applying after-control 'reliably' on 'experiment'
[2023-06-14T12:50:37.525456+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-06-14T12:50:37.525660+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-06-14T12:50:37.525783+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-06-14T12:50:37.525902+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-06-14T12:50:37.526010+00:00 INFO] [experiment:248] Finishing Reliably execution...
[2023-06-14T12:50:37.988488+00:00 DEBUG] [experiment:163] Stopping Reliably state checker now
[2023-06-14T12:50:37.988957+00:00 DEBUG] [experiment:494] Completing execution '91622163-dbe5-480a-96c4-de18cc5374ca' status: completed
[2023-06-14T12:50:38.416658+00:00 DEBUG] [experiment:587] Sending plan '6de80c44-9b7c-4de5-8ff0-7a41f44e8f7b' status: completed
[2023-06-14T12:50:38.747450+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'finished', 'status': 'completed', 'deviated': False, 'plan_id': '6de80c44-9b7c-4de5-8ff0-7a41f44e8f7b'}
[2023-06-14T12:50:39.304877+00:00 INFO] [experiment:311] Finished Reliably execution. Bye!
[2023-06-14T12:50:39.305135+00:00 DEBUG] [caching:42] Clearing activities cache
